name: image_annotation
description: This library provides an easy-to-use solution for adding image annotation capabilities to Flutter applications. With this library, users can draw shapes, add text, highlight specific areas, and resize annotations within a defined picture zone.
version: 0.5.16+156
homepage: https://github.com/MikitaDrazdou/image_annotation

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

example:
  - name: "Simple Example"
    description: "Showing all the possible annotations"
    path: example/main.dart
